### ISSUE TITLE
Crash when no running notification service

### ISSUE THREAD

**Issue by SilverRainZ** [SilverRainZ/srain#112]
```
/ la @ la-mbp 11:41 -> ~  
\ $ systemctl --user status xfce4-notifyd.service 
● xfce4-notifyd.service - XFCE notifications service
   Loaded: loaded (/usr/lib/systemd/user/xfce4-notifyd.service; static; vendor preset: enabled)
   Active: inactive (dead)
```

```
(srain-dev:9386): GLib-GIO-WARNING **: 11:38:33.404: unable to send notifications through org.freedesktop.Notifications: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.freedesktop.Notifications exited with status 1

Thread 1 "srain-dev" received signal SIGSEGV, Segmentation fault.
0x00007ffff68c3f90 in g_slist_remove () from /usr/lib/libglib-2.0.so.0
#0  0x00007ffff68c3f90 in g_slist_remove () at /usr/lib/libglib-2.0.so.0
#1  0x00007ffff6ec4209 in  () at /usr/lib/libgio-2.0.so.0
#2  0x00007ffff6e50204 in  () at /usr/lib/libgio-2.0.so.0
#3  0x00007ffff6e50d07 in  () at /usr/lib/libgio-2.0.so.0
#4  0x00007ffff6e85bf2 in  () at /usr/lib/libgio-2.0.so.0
#5  0x00007ffff6e50204 in  () at /usr/lib/libgio-2.0.so.0
#6  0x00007ffff6e50239 in  () at /usr/lib/libgio-2.0.so.0
#7  0x00007ffff68a51d6 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#8  0x00007ffff68a55b1 in  () at /usr/lib/libglib-2.0.so.0
#9  0x00007ffff68a563e in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#10 0x00007ffff6e6697e in g_application_run () at /usr/lib/libgio-2.0.so.0
#11 0x000055555555e09e in main (argc=1, argv=0x7fffffffe2a8) at core/srain.c:52
A debugging session is active.

	Inferior 1 [process 9386] will be killed.
```

**Comment by SilverRainZ** [comment]
It seems to be a problem with glib, but I can not reroduce on debug version of glib.

closed.
