### ISSUE TITLE
crash in irc.c:irc_parse()

### ISSUE THREAD

**Issue by SilverRainZ** [SilverRainZ/srain#19]
看起来依然是只有连接到多个 server 的时候才崩？

backtrace:

```
(gdb) bt
#0  0x00007ffff4ef4a6d in __strstr_sse2_unaligned ()
   from /usr/lib/libc.so.6
#1  0x0000000000411031 in irc_parse (
    ircbuf=0x8d4590 ":teleboto!~teleboto@104.236.136.84", 
    ircmsg=0x7fffd4001cd0) at irc/irc_parse.c:85
#2  0x0000000000411d6a in irc_recv (irc=0x8d4208, ircmsg=0x7fffd4001cd0)
    at irc/irc.c:173
#3  0x0000000000410894 in server_recv (srv=0x8d4000)
    at server/server.c:148
#4  0x00000000004105d0 in _server_connect (srv=0x8d4000)
    at server/server.c:83
#5  0x00007ffff5bcc975 in ?? () from /usr/lib/libglib-2.0.so.0
#6  0x00007ffff5204424 in start_thread () from /usr/lib/libpthread.so.0
#7  0x00007ffff4f43cbd in clone () from /usr/lib/libc.so.6
```

**Comment by LastAvenger** [comment]
```
(gdb) bt
#0  0x00007ffff4ef4a6d in __strstr_sse2_unaligned () from /usr/lib/libc.so.6
#1  0x00000000004110d5 in irc_parse (ircbuf=0xb3ad90 ":teleboto!~teleboto@104.236.136.84", ircmsg=0x7fffd00092a0) at irc/irc_parse.c:87
#2  0x0000000000411fdc in irc_recv (irc=0xb3aa08, ircmsg=0x7fffd00092a0) at irc/irc.c:173
#3  0x0000000000410894 in server_recv (srv=0xb3a800) at server/server.c:148
#4  0x00000000004105d0 in _server_connect (srv=0xb3a800) at server/server.c:83
#5  0x00007ffff5bcc975 in ?? () from /usr/lib/libglib-2.0.so.0
#6  0x00007ffff5204424 in start_thread () from /usr/lib/libpthread.so.0
#7  0x00007ffff4f43cbd in clone () from /usr/lib/libc.so.6
```
