### ISSUE TITLE
Srain likely segfault after QUIT

### ISSUE THREAD

**Issue by SilverRainZ** [SilverRainZ/srain#58]
触发：在一个已连接到服务器的对话窗口输入 `/quit` 指令。

# 第一次

Backtrace:
```
Thread 7 "srain" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd0bb9700 (LWP 9936)]
0x00007ffff60c6d00 in g_io_stream_get_input_stream () from /usr/lib/libgio-2.0.so.0
(gdb) bt
#0  0x00007ffff60c6d00 in g_io_stream_get_input_stream () at /usr/lib/libgio-2.0.so.0
#1  0x0000000000417721 in  ()
#2  0x0000000000417787 in  ()
#3  0x0000000000417fbc in  ()
#4  0x00007ffff5b6f175 in  () at /usr/lib/libglib-2.0.so.0
#5  0x00007ffff4f052e7 in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007ffff4c4654f in clone () at /usr/lib/libc.so.6
(gdb) 
```
在连接到 freenode 的时候复现机率极大，在 stream 在 free 后，仍然能通过其他线程中的 G_IS_IO_STREAM() 的 check，怀疑 GType 类型系统不是 thread-safe 的，然而能力不足以去查证。

方案：将所有网络函数改为主线程中的异步函数，此 backtrace 至今没有再出现过。

另，`sirc_disconnect()` 后立即 `sirc_free()` 会让异步的 `on_recv()` 函数里面的 stream 无效。于是需要保证 `sirc_free()` 始终在 `DISCONNECT` 事件后再执行，因此修改了部分事件逻辑。

# 第二次

```
Thread 1 "srain" received signal SIGSEGV, Segmentation fault.
0x00007ffff60c4f30 in g_io_stream_get_input_stream () from /usr/lib/libgio-2.0.so.0
#0  0x00007ffff60c4f30 in g_io_stream_get_input_stream () at /usr/lib/libgio-2.0.so.0
#1  0x0000000000418f90 in sirc_recv ()
#2  0x000000000041932b in on_recv ()
#3  0x00007ffff60c2aaa in  () at /usr/lib/libgio-2.0.so.0
#4  0x00007ffff60ea6b3 in  () at /usr/lib/libgio-2.0.so.0
#5  0x00007ffff60ea6e9 in  () at /usr/lib/libgio-2.0.so.0
#6  0x00007ffff5b4466a in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#7  0x00007ffff5b44a20 in  () at /usr/lib/libglib-2.0.so.0
#8  0x00007ffff5b44acc in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#9  0x00007ffff610000d in g_application_run () at /usr/lib/libgio-2.0.so.0
#10 0x0000000000410c2f in sui_main_loop ()
#11 0x0000000000407edb in main ()
A debugging session is active.

	Inferior 1 [process 2175] will be killed.
```

现在 `server_free()` 出现了奇怪的 coredump，崩溃在一堆 mainloop 相关的库函数内部。无法稳定复现。
^ 这种 backtrace 大概是因为程序崩在某个  callback 的内部导致的 :( Async sucks。

**Comment by SilverRainZ** [comment]
Try to fix in 4966deb2f53259b996a22c64307b3e51137ccab0

Do not add a message into chat after the server if freed.
